### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by ghost** [greatwhitehat/faceoff#2]
Hi,
Could you possibly add recursion over subfolders to this script? I really enjoy it; it has been very helpful to me.

**Comment by greatwhitehat** [comment]
Hello,
I honestly did not think anyone used this :-) Happy to hear that it is helpful.

I have not touched this for two years, but I will dedicate some of my time to work on a solution for this request.

So, a question back to you; Would a simple "--recursive" suffice for the command line to have the script to process sub-directories?
I do not want to make it the default, in case that would break something for someone.

**Comment by ghost** [comment]
Yes a flag would be great. Would it be possible to use a recursive function with os.walk? That way the sub folders are searched as long as the sub sub folders as long as the sub sub sub folder etc.

**Comment by greatwhitehat** [comment]
I’ll start looking into this

**Comment by greatwhitehat** [comment]
Can you check if this update works for you please?

**Comment by ghost** [comment]
It works. However, is it possible to disable the copying of pictures that don't have any faces present?

**Comment by greatwhitehat** [comment]
Yes, I can add a flag for that. But I’ll can close this issue now at least :-)
